# Generated by Django 5.2.6 on 2025-09-08 10:24

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.upload_to)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='research',
            name='pdf',
        ),
        migrations.AddField(
            model_name='research',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=content.models.upload_to),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.upload_to),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(upload_to=content.models.upload_to),
        ),
        migrations.AlterField(
            model_name='research',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.upload_to),
        ),
    ]
